import { Activity, IconOption, Subject } from "./common-types";

export const AVAILABLE_ICONS: IconOption[] = [
  { id: "book", value: "📚", category: "education" },
  { id: "pencil", value: "✏️", category: "education" },
  { id: "ruler", value: "📏", category: "education" },
  { id: "calculator", value: "🧮", category: "education" },
  { id: "globe", value: "🌍", category: "geographie" },
  { id: "atom", value: "⚛️", category: "science" },
  { id: "microscope", value: "🔬", category: "science" },
  { id: "test-tube", value: "🧪", category: "science" },
  { id: "dna", value: "🧬", category: "science" },
  { id: "math", value: "➗", category: "mathematiques" },
  { id: "literature", value: "📖", category: "litterature" },
  { id: "history", value: "🏛️", category: "histoire" },
  { id: "art", value: "🎨", category: "art" },
  { id: "music", value: "🎵", category: "musique" },
  { id: "sports", value: "🏃", category: "sports" },
  { id: "soccer", value: "⚽", category: "sports" },
  { id: "basketball", value: "🏀", category: "sports" },
  { id: "volleyball", value: "🏐", category: "sports" },
  { id: "tennis", value: "🎾", category: "sports" },
  { id: "swimming", value: "🏊", category: "sports" },
  { id: "cycling", value: "🚴", category: "sports" },
  { id: "running", value: "🏃‍♂️", category: "sports" },
  { id: "gym", value: "🏋️", category: "sports" },
  { id: "yoga", value: "🧘", category: "sports" },
  { id: "dance", value: "💃", category: "arts" },
  { id: "cooking", value: "👨‍🍳", category: "loisir" },
  { id: "gardening", value: "🌱", category: "loisir" },
  { id: "gaming", value: "🎮", category: "loisir" },
  { id: "coding", value: "💻", category: "technologie" },
  { id: "language", value: "🗣️", category: "langue" },
  { id: "english", value: "🇬🇧", category: "langue" },
  { id: "french", value: "🇫🇷", category: "langue" },
  { id: "spanish", value: "🇪🇸", category: "langue" },
  { id: "german", value: "🇩🇪", category: "langue" },
  { id: "italian", value: "🇮🇹", category: "langue" },
  { id: "chinese", value: "🇨🇳", category: "langue" },
  { id: "japanese", value: "🇯🇵", category: "langue" },
  { id: "arabic", value: "🇸🇦", category: "langue" },
  { id: "russian", value: "🇷🇺", category: "langue" },
  { id: "portuguese", value: "🇵🇹", category: "langue" },
  { id: "painting", value: "🖌️", category: "art" },
  { id: "photography", value: "📷", category: "art" },
  { id: "theatre", value: "🎭", category: "art" },
  { id: "cinema", value: "🎬", category: "art" },
  { id: "astronomy", value: "🔭", category: "science" },
  { id: "ecology", value: "🌿", category: "science" },
  { id: "medical", value: "⚕️", category: "science" },
  { id: "engineering", value: "⚙️", category: "technologie" },
];

export const AVAILABLE_SUBJECTS: Omit<Subject, "id" | "teachers">[] = [
  { name: "Mathématiques", shortName: "Math", color: "#3b82f6", icon: "➗" },
  { name: "Physique", shortName: "Phys", color: "#8b5cf6", icon: "⚛️" },
  { name: "Chimie", shortName: "Chim", color: "#10b981", icon: "🧪" },
  { name: "Biologie", shortName: "Bio", color: "#22c55e", icon: "🧬" },
  { name: "Informatique", shortName: "Info", color: "#06b6d4", icon: "💻" },
  { name: "Anglais", shortName: "Ang", color: "#ef4444", icon: "🇬🇧" },
  { name: "Français", shortName: "Fr", color: "#d946ef", icon: "🇫🇷" },
  { name: "Espagnol", shortName: "Esp", color: "#f97316", icon: "🇪🇸" },
  { name: "Allemand", shortName: "All", color: "#eab308", icon: "🇩🇪" },
  { name: "Histoire", shortName: "Hist", color: "#f59e0b", icon: "🏛️" },
  { name: "Géographie", shortName: "Géo", color: "#84cc16", icon: "🌍" },
  { name: "Arts Plastiques", shortName: "Art", color: "#ec4899", icon: "🎨" },
  { name: "Musique", shortName: "Mus", color: "#0ea5e9", icon: "🎵" },
  {
    name: "Éducation Physique",
    shortName: "EPS",
    color: "#14b8a6",
    icon: "🏃",
  },
  { name: "Économie", shortName: "Éco", color: "#6366f1", icon: "📊" },
  { name: "Gestion", shortName: "Gest", color: "#a855f7", icon: "💼" },
  { name: "Psychologie", shortName: "Psy", color: "#f43f5e", icon: "🧠" },
  { name: "Sociologie", shortName: "Socio", color: "#3b82f6", icon: "👥" },
  { name: "Philosophie", shortName: "Philo", color: "#ef4444", icon: "🤔" },
  {
    name: "Éducation Religieuse",
    shortName: "ER",
    color: "#84cc16",
    icon: "🕌",
  },
  { name: "Italien", shortName: "Ita", color: "#f97316", icon: "🇮🇹" },
  { name: "Portugais", shortName: "Port", color: "#0ea5e9", icon: "🇵🇹" },
  { name: "Russe", shortName: "Rus", color: "#d946ef", icon: "🇷🇺" },
  { name: "Chinois", shortName: "Chi", color: "#10b981", icon: "🇨🇳" },
  { name: "Japonais", shortName: "Jap", color: "#8b5cf6", icon: "🇯🇵" },
  { name: "Arabe", shortName: "Ara", color: "#f59e0b", icon: "🇸🇦" },
  { name: "Latin", shortName: "Lat", color: "#ef4444", icon: "🏛️" },
  { name: "Grec", shortName: "Grec", color: "#3b82f6", icon: "🏺" },
  { name: "Littérature", shortName: "Lit", color: "#ec4899", icon: "📖" },
  { name: "Théâtre", shortName: "Théa", color: "#a855f7", icon: "🎭" },
  { name: "Droit", shortName: "Droit", color: "#6366f1", icon: "⚖️" },
  {
    name: "Sciences Politiques",
    shortName: "Pol",
    color: "#14b8a6",
    icon: "🗳️",
  },
  { name: "Ingénierie", shortName: "Ing", color: "#84cc16", icon: "⚙️" },
  { name: "Architecture", shortName: "Arch", color: "#f43f5e", icon: "🏗️" },
  { name: "Médecine", shortName: "Med", color: "#0ea5e9", icon: "⚕️" },
];

export const AVAILABLE_ACTIVITIES: Omit<Activity, "id">[] = [
  { name: "Football", shortName: "Foot", color: "#22c55e", icon: "⚽" },
  { name: "Basketball", shortName: "Basket", color: "#f97316", icon: "🏀" },
  { name: "Volleyball", shortName: "Volley", color: "#3b82f6", icon: "🏐" },
  { name: "Tennis", shortName: "Tennis", color: "#84cc16", icon: "🎾" },
  { name: "Natation", shortName: "Nat", color: "#0ea5e9", icon: "🏊" },
  { name: "Course", shortName: "Course", color: "#ef4444", icon: "🏃‍♂️" },
  { name: "Musculation", shortName: "Muscu", color: "#6366f1", icon: "🏋️" },
  { name: "Yoga", shortName: "Yoga", color: "#d946ef", icon: "🧘" },
  { name: "Danse", shortName: "Danse", color: "#ec4899", icon: "💃" },
  { name: "Club d'Art", shortName: "Art", color: "#f43f5e", icon: "🎨" },
  {
    name: "Groupe de Musique",
    shortName: "Musique",
    color: "#0ea5e9",
    icon: "🎵",
  },
  {
    name: "Club de Théâtre",
    shortName: "Théâtre",
    color: "#a855f7",
    icon: "🎭",
  },
  { name: "Club d'Échecs", shortName: "Échecs", color: "#f59e0b", icon: "♟️" },
  {
    name: "Club de Programmation",
    shortName: "Code",
    color: "#06b6d4",
    icon: "💻",
  },
  {
    name: "Club de Sciences",
    shortName: "Sciences",
    color: "#10b981",
    icon: "🔬",
  },
  { name: "Club de Débat", shortName: "Débat", color: "#ef4444", icon: "🎤" },
  {
    name: "Club de Lecture",
    shortName: "Lecture",
    color: "#8b5cf6",
    icon: "📚",
  },
  {
    name: "Club de Photographie",
    shortName: "Photo",
    color: "#14b8a6",
    icon: "📷",
  },
  {
    name: "Club de Cuisine",
    shortName: "Cuisine",
    color: "#f97316",
    icon: "👨‍🍳",
  },
  {
    name: "Club de Jardinage",
    shortName: "Jardin",
    color: "#84cc16",
    icon: "🌱",
  },
  { name: "Handball", shortName: "Hand", color: "#3b82f6", icon: "🤾" },
  { name: "Rugby", shortName: "Rugby", color: "#ef4444", icon: "🏉" },
  { name: "Badminton", shortName: "Bad", color: "#f59e0b", icon: "🏸" },
  { name: "Athlétisme", shortName: "Athlé", color: "#22c55e", icon: "🏃‍♂️" },
  { name: "Gymnastique", shortName: "Gym", color: "#d946ef", icon: "🤸‍♀️" },
  { name: "Escalade", shortName: "Escal", color: "#a855f7", icon: "🧗‍♂️" },
  { name: "Cyclisme", shortName: "Vélo", color: "#06b6d4", icon: "🚴" },
  {
    name: "Club de Robotique",
    shortName: "Robot",
    color: "#10b981",
    icon: "🤖",
  },
  { name: "Club de Cinéma", shortName: "Ciné", color: "#ec4899", icon: "🎬" },
  { name: "Chorale", shortName: "Chant", color: "#0ea5e9", icon: "🎤" },
  { name: "Orchestre", shortName: "Orch", color: "#6366f1", icon: "🎻" },
  {
    name: "Club d'Astronomie",
    shortName: "Astro",
    color: "#8b5cf6",
    icon: "🔭",
  },
  { name: "Club d'Écologie", shortName: "Éco", color: "#84cc16", icon: "🌿" },
  { name: "Club d'Histoire", shortName: "Hist", color: "#f59e0b", icon: "🏛️" },
  { name: "Arts Martiaux", shortName: "AM", color: "#ef4444", icon: "🥋" },
];

export function generateUniqueId(prefix: string): string {
  return `${prefix}-${Math.random().toString(36).substring(2, 9)}`;
}

// Fonctions pour créer une nouvelle Matière ou Activité avec des identifiants générés
export function createNewSubject(
  data: Omit<Subject, "id" | "teachers">
): Subject {
  return {
    ...data,
    id: generateUniqueId("s"),
    teachers: [],
  };
}

export function createNewActivity(data: Omit<Activity, "id">): Activity {
  return {
    ...data,
    id: generateUniqueId("a"),
  };
}
